name: Deploy .NET Web App

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Ensure this matches your project version

      - name: Restore Dependencies
        run: dotnet restore D:/CMS Projects/Meghalaya/FinalCode/MeghalayaUIP.sln  # Change "D:/CMS Projects/Meghalaya/FinalCode/MeghalayaUIP.sln" to your actual solution file path

      - name: Build Project
        run: dotnet build D:/CMS Projects/Meghalaya/FinalCode/MeghalayaUIP.sln --configuration Release --no-restore

      - name: Publish Project
        run: dotnet publish D:/CMS Projects/Meghalaya/FinalCode/MeghalayaUIP.sln -c Release -o published

      - name: Deploy to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          source: "published/*"
          target: "/GITPASS"  # Change to your target folder
