name: Deploy to Windows Server

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: windows-latest  # GitHub-hosted runner (Windows)
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Sync Code to Remote Windows Server
        run: |
          $password = ConvertTo-SecureString '9jfxudfvSRC5KT%929' -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ('Administrator', $password)

          Invoke-Command -ComputerName 10.9.246.173 -Credential $credential -ScriptBlock {
              param($source, $destination)
              Copy-Item -Path $source -Destination $destination -Recurse -Force
          } -ArgumentList "D:\CMS Projects\Meghalaya\gitcode", "D:\Kalyanbabu\UPRERA\gitcmscode"
